### ISSUE TITLE
No error handling for malformed config file

### ISSUE THREAD

**Issue by MysticMia** [giggletech/GiggleTech_OSC_Router#12]
If the config.yml file has invalid syntax, the server quits as soon as it starts up, without any explanation popup.

**Expected:**
The app gives a popup modal explaining the error (malformed config file), optionally loading default settings or closing after.

**Example:**
I changed `default_use_velocity_control: false` to `True` instead of `true`, and the app closed without warning. Removing the colon (:) before the `false` results in the same.

**Comment by giggletech** [comment]
Heya!

Ive added error handling for the True/true issue you brought up, and added detail to the error logs if there is a configuration issue.

See the latest release here :https://github.com/giggletech/GiggleTech_OSC_Router/releases/tag/v1.3.2
