### ISSUE TITLE
Keep (add?) Linux support - appears to build and run, not tested hardware

### ISSUE THREAD

**Issue by digitalf0x** [giggletech/GiggleTech_OSC_Router#8]
## In brief
* Keep (or add?) support for Linux as a VR platform
  * [Windows-specific additions are fine](https://github.com/giggletech/GiggleTech_OSC_Router/pull/6 ), but ensure the core functionality works on Linux

## Rationale
Today, the GiggleTech OSC Router appears to build and run on Linux (`rustup default stable`, `cargo build`, etc), and while I lack the hardware to properly test this, I skimmed through the Rust code and nothing stands out as incompatible.

VR (including SteamVR) on Linux continues to improve with various headsets today, and with rumors of Valve's next headset building upon their SteamOS 3.0 Linux foundations, keeping (or adding) Linux support would provide a solid head start.

This might also permit implicitly promoting the Giggle Puck hardware by adding it to several community Linux VR sites, such as…
* [VR Software and Hardware on Linux - gitlab/vr-on-linux](https://gitlab.com/vr-on-linux/VR-on-Linux )
* [Linux VR Adventures, including software and hardware - lvra.gitlab.io](https://lvra.gitlab.io/ )

Personally, I've been using SteamVR on Linux for over a year, including adding full-body haptics to my Tundra Trackers with the VRC Haptic Pancake's Python GUI software on Linux (I have an open PR for prototyping the Tundra Trackers' quirks).  With plans to add external device support, it might even be possible to integrate the Giggle Puck directly as an OSC target alongside the existing OpenVR target.

I'm strongly interested in buying a Giggle Puck for myself and a friend using SteamVR on Linux, but it would be nice to know that we'll be able to start/keep using the software in the future.  I realize you likely won't be able to offer customer support (Linux VR is more complex); this is just about keeping the minimum software functional.

**Comment by giggletech** [comment]
Noted, and will test on a Linux system.

**Comment by Beethoven-n** [comment]
i'd buy the gigglepuck right away if i got a definitive "yes, it works on linux"

**Comment by giggletech** [comment]
> i'd buy the gigglepuck right away if i got a definitive "yes, it works on linux"

Im looking to get running on Linux VR, I will update you once I have it confirmed

-Sideways

**Comment by giggletech** [comment]
Video showing GigglePucks running on Linux

https://youtu.be/1Uq79IgEDoA?si=XddpocPTqc82HX0Z

@Beethoven-n @digitalf0x

**Comment by digitalf0x** [comment]
@giggletech That's awesome, thank you!  I felt like it should work (it looked like mostly math and network, nothing platform specific), but having you test it with the actual hardware confirms this.

I think this issue can be closed as done, and I've added the GigglePuck to my future VR budget =^.^=

(It may be a while - in recent weeks, I've been helping some friends add haptics motors inside their existing Tundra Trackers, which would complement the GigglePuck.  Short version: Vybronics' dual magnet VCDM1027B003L is robust and fast responding, without being so intense as to cause tracker drift like the punchy VC1434B002U.  LRAs such as what Tundra ships with their IO Boards are amazingly precise, but need direct contact - body straps muffle them too much.)
